# Compiler settings
CXX := g++
CXXFLAGS := -g -Wall -fpermissive -std=c++17

# SFML Paths
# The libraries are located in the 'build' directory generated by CMake
SFML_BUILD_PATH := build/_deps
SFML_INCLUDE := -I$(SFML_BUILD_PATH)/sfml-src/include
SFML_LIB := -L$(SFML_BUILD_PATH)/sfml-build/lib

LDFLAGS := $(SFML_LIB) -lsfml-graphics -lsfml-window -lsfml-system

# Directories
SRC_DIR := .
OBJ_DIR := obj

# Files
SRC_FILES := $(wildcard $(SRC_DIR)/*.cpp)
OBJ_FILES := $(patsubst $(SRC_DIR)/%.cpp,$(OBJ_DIR)/%.o,$(SRC_FILES))
TARGET := mandelbrot

# Phony targets ensure commands run even if files with these names exist
.PHONY: all run clean

all: $(TARGET)

$(TARGET): $(OBJ_FILES)
	$(CXX) -o $@ $^ $(LDFLAGS)

# Create the object directory if it doesn't exist, then compile
$(OBJ_DIR)/%.o: $(SRC_DIR)/%.cpp | $(OBJ_DIR)
	$(CXX) $(CXXFLAGS) $(SFML_INCLUDE) -c -o $@ $<

$(OBJ_DIR):
	mkdir -p $(OBJ_DIR)

run: all
	./$(TARGET)

clean:
	rm -rf $(OBJ_DIR) $(TARGET)